
experiment:
  name: "moco"
  seed: 1
  mounted_dir: "/data/pa_cpgarchive/projects/chimera/"
  save_dir: "/data/temporary/filip/MMCLR/experiments/"

data:
  clinical_path: "/data/pa_cpgarchive/projects/chimera/_aws/task1/clinical_data/"
  main_dir: "/data/pa_cpgarchive/projects/chimera/_aws/task1/"

  
model:
  base_model_type: "ViT"
  clinical_input_dim: 14
  clinical_hidden_dim: 512
  clinical_output_dim: 1024 
  feature_dim: 1024
  perceiver_output_dim: 1000
  num_modalities: 3
  num_features: 2308 #(48*48 + 1 + 3)
  mri_feature_encoder: "resnet"
  mri_resnet_weights: "model_weights/weights_from_daan.pth"

moco:
  K: 4096
  dim: 1024
  m: 0.999
  T: 0.07


training:
  wsi_grid_size: 48
  epochs: 99
  virtual_batch_size: 48
  batch_size: 4
  learning_rate: 0.0001
  optimizer: "Adam"
  opt_hparams: 
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.01
  clinical_dropout: 0.25
  mri_dropout: 0.20
