experiment:
  name: "surv_moco"
  objective: "surv"
  seed: 1
  mounted_dir: "/data/pa_cpgarchive/projects/chimera/"
  save_dir: "/data/temporary/filip/MMCLR/experiments/"

data:
  clinical_path: "/data/pa_cpgarchive/projects/chimera/_aws/task1/clinical_data/"
  main_dir: "/data/pa_cpgarchive/projects/chimera/_aws/task1/"
  num_time_bins: 10

validation:
  clinical_path: "/data/pa_cpgarchive/projects/chimera/_gc/task1/val/clinical_data/"
  main_dir: "/data/pa_cpgarchive/projects/chimera/_gc/task1/val/"

  
model:
  num_time_bins: 10
  type: "admil"


training:
  loss: "nll" 
  alpha: 0.15
  wsi_grid_size: 48
  epochs: 50
  batch_size: 1
  learning_rate: 0.0001
  optimizer: "Adam"
  opt_hparams: 
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.01
  clinical_dropout: 0.25