experiment:
  name: "surv_super"
  objective: "surv"
  seed: 1
  mounted_dir: "/data/pa_cpgarchive/projects/chimera/"
  save_dir: "/data/temporary/filip/MMCLR/experiments/"
  main_dir: "/data/temporary/filip/cohorts/cwz_retrospective"

data:
  pathology_dir: "/data/temporary/filip/cohorts/cwz_retrospective/wsi_embeddings/prism"
  radiology_dir: "/data/pa_cpgarchive/projects/chimera/_aws/task1/radiology/images"
  clinical_vars: 
  - "anon_pid" 
  - "age_at_prostatectomy"
  - "ISUP"
  - "pre_operative_PSA"
  - "pT_stage"
  - "positive_lymph_nodes"
  - "capsular_penetration"
  - "positive_surgical_margins"
  - "invasion_seminal_vesicles"
  - "lymphovascular_invasion"
  
model:
  num_time_bins: 5
  feature_dim: 1280

training:
  loss: "nll" 
  alpha: 0.15
  epochs: 50
  batch_size: 1
  learning_rate: 1e-6
  optimizer: "Adam"
  opt_hparams: 
    betas: [0.9, 0.999]
    eps: 1.0e-08
    weight_decay: 0.05
  clinical_dropout: 0.25